x-templates:
  agent_centos7_altarch:
    &agent_centos7_altarch
    image: harbor.einscat.com:10011/library/centos7:altarch
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ~/workspace:/root/workspace
  agent_centos8_aarch64:
    &agent_centos8_aarch64
    image: harbor.einscat.com:10011/library/centos8:aarch64
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ~/workspace:/root/workspace

services:

  vm-1:
    container_name: vm-1
    hostname: "vm-1"
    networks:
      vm_net:
        ipv4_address: 172.20.30.1
      vm_net2:
        ipv4_address: 172.20.40.1
    ports:
      - "13306:3306"
      - "16379:6379"
      - "10001:10000"
      - "20001:18080"
      - "20002:27001"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "~/workspace:/root/workspace"
    <<: *agent_centos7_altarch

  vm-2:
    container_name: vm-2
    hostname: "vm-2"
    networks:
      vm_net:
        ipv4_address: 172.20.30.2
      vm_net2:
        ipv4_address: 172.20.40.2
    ports:
      - "13307:3306"
      - "16380:6379"
    <<: *agent_centos7_altarch

  vm-3:
    container_name: vm-3
    hostname: "vm-3"
    networks:
      vm_net:
        ipv4_address: 172.20.30.3
      vm_net2:
        ipv4_address: 172.20.40.3
    ports:
      - "13308:3306"
      - "16381:6379"
    <<: *agent_centos7_altarch

  vm-4:
    container_name: vm-4
    hostname: "vm-4"
    networks:
      vm_net:
        ipv4_address: 172.20.30.4
      vm_net2:
        ipv4_address: 172.20.40.4
    ports:
      - "13309:3306"
      - "16382:6379"
    <<: *agent_centos7_altarch

  vm-5:
    container_name: vm-5
    hostname: "vm-5"
    networks:
      vm_net:
        ipv4_address: 172.20.30.5
      vm_net2:
        ipv4_address: 172.20.40.5
    ports:
      - "13310:3306"
      - "16383:6379"
    <<: *agent_centos7_altarch

  vm-6:
    container_name: vm-6
    hostname: "vm-6"
    networks:
      vm_net:
        ipv4_address: 172.20.30.6
      vm_net2:
        ipv4_address: 172.20.40.6
    ports:
      - "13311:3306"
      - "16384:6379"
    <<: *agent_centos8_aarch64

  vm-7:
    container_name: vm-7
    hostname: "vm-7"
    networks:
      vm_net:
        ipv4_address: 172.20.30.7
      vm_net2:
        ipv4_address: 172.20.40.7
    ports:
      - "13312:3306"
      - "16385:6379"
    <<: *agent_centos8_aarch64

  vm-8:
    container_name: vm-8
    hostname: "vm-8"
    networks:
      vm_net:
        ipv4_address: 172.20.30.8
      vm_net2:
        ipv4_address: 172.20.40.8
    ports:
      - "13313:3306"
      - "16386:6379"
    <<: *agent_centos8_aarch64

  vm-9:
    container_name: vm-9
    hostname: "vm-9"
    networks:
      vm_net:
        ipv4_address: 172.20.30.9
      vm_net2:
        ipv4_address: 172.20.40.9
    ports:
      - "13314:3306"
      - "16387:6379"
    <<: *agent_centos8_aarch64

  vm-10:
    container_name: vm-10
    hostname: "vm-10"
    networks:
      vm_net:
        ipv4_address: 172.20.30.10
      vm_net2:
        ipv4_address: 172.20.40.10
    ports:
      - "13315:3306"
      - "16388:6379"
    <<: *agent_centos8_aarch64

networks:
  vm_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.30.0/24
          gateway: 172.20.30.254
  vm_net2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.40.0/24
          gateway: 172.20.40.254

